version: '3'
services:
  elasticsearch:
    image: martingiannechini/elastic
    container_name: elasticsearch
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    network_mode: "host"
  application:
    image: martingiannechini/stubdpval:0.5
    container_name: app
    environment:
      NODE_ENV: PROD_HOST
    ports:
      - 80:80
    depends_on:
      - elasticsearch
    network_mode: "host"
volumes:
  esdata1:
    driver: local

